MAGNITUDE_EPSILON = 1
TOP_LEFT = (0, 0)
RED_COLOR = (212, 89, 80)

DEFAULT_FONT = "Arial"
DEFAULT_FONT_SCALE_FACTOR = 50
DEFAULT_FONT_COLOR = (0, 0, 0)

# Tasks

HIGHEST_TASK_PRIORITY = 0
LOWEST_TASK_PRIORITY = 15

# Collision Directions

COLLISION_UP = 0
COLLISION_RIGHT = 1
COLLISION_DOWN = 2
COLLISION_LEFT = 3
